springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.example.zlv
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn

server:
  port: 8123

ai:
  ollama:
    apiHost: "http://localhost.zlv.com:11434"
  websearch:
    searxng:
      url: "http://localhost.zlv.com:8080/search"
      nums: 10
      engines: "bing,duckduckgo,brave,mojeek,qwant,semantic_scholar"


spring:
  application:
    name: ai
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: deepseek-r1:7b
#  openai:
#    base-url: https://dashscop.aliyuncs.com/compatible-mode
#    api-key: ${OPENAI_API_KEY}
#    chat:
#      options:
#        model: qwen-max # 模型名称
#        temperature: 0.8 # 模型温度，值越大，输出结果越随机
logging:
  level:
    org.springframework.ai.chat.client.advisor: debug
    com.example.zlv.controller: debug