spring.application.name=zlv
spring.mvc.static-path-patten=/static/**
ollama.generate.url=http://localhost:11434/api/generate
ollama.chat.url=http://localhost:11434/api/chat
search.url=http://localhost.zlv.com:8080/search